Add options out parameter.
concourse/git-resource pull request #397
Opened 2023-01-30 15:32 UTC by romain-dartigues

This parameter let the Concourse resource to set the `--push-option`.

* https://git-scm.com/docs/git-push#Documentation/git-push.txt---push-optionltoptiongt
* https://gitlab.com/gitlab-org/gitlab/-/blob/v15.8.0-ee/doc/user/project/push_options.md

2023-01-31 08:21 UTC, romain-dartigues commented
(review requested, especially do you think it should support multiple options?)

2023-09-18 20:37 UTC, taylorsilva commented
What's the usecase you imagine for this? I mechanically understand what you're adding here, but I don't know _when_ I would use this? Do you have an example?

2023-09-29 12:28 UTC, romain-dartigues commented
Hi Taylor,
my apologies, I haven't seen the notification.

One obvious use-case would be the one in the GitLab link, ie: `--push-option=ci.skip` (and/or add add variables required to trigger some parts of the pipeline through `-o ci.variable="foo=bar"`).

In my case, one of the project hosted on a GitLab use a mix of Concourse pipelines and GitLab CI pipelines; being able to disable or trigger the GitLab pipeline trough the `git-resource` of Concourse would be useful.

2024-04-05 15:00 UTC, taylorsilva requested changes
Sorry for the delay, lots of stuff to look at across all the repos!

Noticing we have no test here for this and we should add one I think: https://github.com/concourse/git-resource/blob/master/test/put.sh

2025-05-31 15:46 UTC, taylorsilva commented
Closing because stale. Feel free to re-open/re-submit with added tests.

2025-05-31 15:46 UTC, closed without merging